version: '3.7'
services:
    app:
        container_name: desafio-aws-amcom-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '80:80'
        env_file:
            - .env
        environment:
            - NODE_ENV=${NODE_ENV}
            - REACT_APP_USERPOOL_ID=${REACT_APP_USERPOOL_ID}
            - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
            - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
